services:
  app:
    build: .
    #container_name: logops_app
    ports:
      - "5000:5000"
    environment:
      - DB_PATH=/app/data/logs.db
    volumes:
      - logops_data:/app/data

  nginx:
    image: nginx:alpine
    #container_name: logops_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
